/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Presentacion.inicio;
import java.awt.Image;
import java.util.Calendar;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Clases.DtNickTitProp;
import logica.Clases.DtinfoPropuesta;
import logica.Fabrica;
import logica.Interfaces.IPropCat;

/**
 *
 * @author gabri
 */
public class ModificarPropuesta extends javax.swing.JInternalFrame {
    private IPropCat IPC;
private DtinfoPropuesta prop;

    public ModificarPropuesta() {
        initComponents();
        prop=null;
        this.IPC = Fabrica.getInstance().getControladorPropCat();
        List<DtNickTitProp> listProp = IPC.listarPropuestas();
        DefaultTableModel modelo = (DefaultTableModel) TablaPropuestas.getModel();

        modelo.setRowCount(0);

        for (int i = 0; i < listProp.size(); i++) {

            DtNickTitProp propu = (DtNickTitProp) listProp.get(i);
            Object[] datos = {propu.getTituloP(), propu.getProponente()};

            modelo.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPropuestas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ModificarDatos = new javax.swing.JButton();
        textRetorno = new javax.swing.JTextField();
        textTitulo1 = new javax.swing.JTextField();
        textcat = new javax.swing.JTextField();
        textfecha = new javax.swing.JTextField();
        textmonto = new javax.swing.JTextField();
        textprecio = new javax.swing.JTextField();
        textlugar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar propuesta");
        setMinimumSize(new java.awt.Dimension(550, 650));
        setPreferredSize(new java.awt.Dimension(600, 650));

        jPanel1.setMinimumSize(new java.awt.Dimension(550, 650));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaPropuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Titulo de Propuesta", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPropuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPropuestas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 310, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Datos de la propuesta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        ModificarDatos.setText("Modificar Datos");
        ModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        textRetorno.setEditable(false);
        textRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRetornoActionPerformed(evt);
            }
        });
        jPanel1.add(textRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 250, -1));

        textTitulo1.setEditable(false);
        textTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTitulo1ActionPerformed(evt);
            }
        });
        jPanel1.add(textTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 250, -1));

        textcat.setEditable(false);
        textcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcatActionPerformed(evt);
            }
        });
        jPanel1.add(textcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 250, -1));

        textfecha.setEditable(false);
        textfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfechaActionPerformed(evt);
            }
        });
        jPanel1.add(textfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 250, -1));

        textmonto.setEditable(false);
        textmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textmontoActionPerformed(evt);
            }
        });
        jPanel1.add(textmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 250, -1));

        textprecio.setEditable(false);
        textprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprecioActionPerformed(evt);
            }
        });
        jPanel1.add(textprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 250, -1));

        textlugar.setEditable(false);
        textlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlugarActionPerformed(evt);
            }
        });
        jPanel1.add(textlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 250, -1));

        jLabel3.setText("Titulo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel4.setText("Categoria:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel5.setText("Fecha de publicacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel6.setText("Monto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel7.setText("Precio de entrada:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel8.setText("Lugar:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel9.setText("Retorno:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel10.setText("Descripcion:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Imagen");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 140, 140));

        TextDesc.setEditable(false);
        TextDesc.setColumns(20);
        TextDesc.setLineWrap(true);
        TextDesc.setRows(5);
        jScrollPane2.setViewportView(TextDesc);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 250, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarDatosActionPerformed
        // TODO add your handling code here:
        if(prop == null){
            JOptionPane.showMessageDialog(null,"Porfavor elija una propuesta primero");
            return;
        }
        ModificarPropuesta2 mp2=new ModificarPropuesta2(prop);
        inicio.Escritorio.add(mp2);
        this.setVisible(false);
        mp2.toFront();
        mp2.setVisible(true);
    }//GEN-LAST:event_ModificarDatosActionPerformed

    private void textRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRetornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRetornoActionPerformed

    private void textTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTitulo1ActionPerformed

    private void textcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcatActionPerformed

    private void textfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfechaActionPerformed

    private void textmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textmontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textmontoActionPerformed

    private void textprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprecioActionPerformed

    private void textlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlugarActionPerformed

    private void TablaPropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPropuestasMouseClicked
        // TODO add your handling code here:
        DtinfoPropuesta dtp= IPC.SeleccionarPropuestaR((String) TablaPropuestas.getValueAt(TablaPropuestas.getSelectedRow(), 0));
       Calendar c = dtp.getFechaReal();
        int dia = c.get(Calendar.DAY_OF_MONTH);
        int mes = c.get(Calendar.MONTH) + 1;
        int anio = c.get(Calendar.YEAR);
       textcat.setText(dtp.getTipoEspec());
       textTitulo1.setText(dtp.getTitulo());
       TextDesc.setText(dtp.getDescripcion());
       textprecio.setText(""+dtp.getPrecio());
      textRetorno.setText(dtp.getTipoRetorno().name());
      textlugar.setText(dtp.getLugar());
      textmonto.setText(""+dtp.getMonto());
      textfecha.setText(dia+"/"+mes+"/"+anio);
       String fotos = System.getProperty("user.dir") + "\\fPropuestas\\" + dtp.getImagen();
        ImageIcon fot = new ImageIcon(fotos);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
        foto.setIcon(icono);
      prop=dtp;
    }//GEN-LAST:event_TablaPropuestasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IPC.resetearPropuesta();
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPropuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPropuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPropuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPropuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPropuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificarDatos;
    private javax.swing.JTable TablaPropuestas;
    private javax.swing.JTextArea TextDesc;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textRetorno;
    private javax.swing.JTextField textTitulo1;
    private javax.swing.JTextField textcat;
    private javax.swing.JTextField textfecha;
    private javax.swing.JTextField textlugar;
    private javax.swing.JTextField textmonto;
    private javax.swing.JTextField textprecio;
    // End of variables declaration//GEN-END:variables
}
