/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.event.MouseAdapter;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.Clases.DtColaboraciones;
import logica.Clases.DtConsultaPropuesta;
import logica.Clases.DtDesactivado;
import logica.Clases.DtinfoColaborador;
import logica.Fabrica;

/**
 *
 * @author Martin
 */
public class VerProponenteDesactivado2 extends javax.swing.JInternalFrame {

    List<DtinfoColaborador> colabs;
    List<String> listProp;

    /**
     * Creates new form VerProponenteDesactivado2
     *
     * @param nickName
     */
    public VerProponenteDesactivado2(String nickName) {
        initComponents();
        this.setTitle("INFORMACION DEL PROPONENTE DESACTIVADO: " + nickName + "");

        DtDesactivado usu = Fabrica.getInstance().getIControladorUsuario().obtenerProponenteDesactivado(nickName);

        if (usu != null) {
            jTextPropNick.setText(usu.getNick());
            jTextPropNombre.setText(usu.getNombre());
            jTextPropApellido.setText(usu.getApellido());
            jTextPropFechaD.setText(usu.getFechaD());
            jTextPropFechaN.setText(usu.getFechaN());
            jTextPropCorreo.setText(usu.getCorreo());

            listProp = Fabrica.getInstance().getControladorPropCat().ListarPropuestasDe(usu.getNick());

            DefaultTableModel modelo = (DefaultTableModel) jTablePropuestas.getModel();

            modelo.setRowCount(0);

            for (int i = 0; i < listProp.size(); i++) {
                Object[] datos = {listProp.get(i)};
                modelo.addRow(datos);
            }
            jTablePropuestas.addMouseListener(new MouseAdapter() {
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelPropuesta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePropuestas = new javax.swing.JTable();
        jTextPropuCategoria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextPropuTitulo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextPropuFechaR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextPropuEstado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextPropuRetorno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextPropuLugar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextPropuMontoT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextPropuPrecioE = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextPropuTotalActual = new javax.swing.JTextField();
        jTextFiltrarPropuestas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanelColaboraciones = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextColabMonto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextColabFecha = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextColabRetorno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableColaboradores = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTextFiltrarColaboraciones = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextColabHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelInfoUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextPropFechaN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextPropNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPropApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextPropNick = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextPropCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextPropFechaD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanelPropuesta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePropuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Titulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePropuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePropuestas);

        jTextPropuCategoria.setEditable(false);

        jLabel8.setText("Categoria:");

        jTextPropuTitulo.setEditable(false);

        jLabel9.setText("Titulo:");

        jTextPropuFechaR.setEditable(false);

        jLabel10.setText("Fecha Realizacion:");

        jTextPropuEstado.setEditable(false);

        jLabel11.setText("Estado:");

        jTextPropuRetorno.setEditable(false);

        jLabel12.setText("Retorno:");

        jTextPropuLugar.setEditable(false);

        jLabel13.setText("Lugar:");

        jTextPropuMontoT.setEditable(false);

        jLabel14.setText("Monto Total:");

        jLabel15.setText("Detalle Propuesta");

        jLabel16.setText("Precio Entrada:");

        jTextPropuPrecioE.setEditable(false);

        jLabel17.setText("Recaudación:");

        jTextPropuTotalActual.setEditable(false);

        jTextFiltrarPropuestas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFiltrarPropuestasKeyReleased(evt);
            }
        });

        jLabel18.setText("Filtrar Propuestas:");

        javax.swing.GroupLayout jPanelPropuestaLayout = new javax.swing.GroupLayout(jPanelPropuesta);
        jPanelPropuesta.setLayout(jPanelPropuestaLayout);
        jPanelPropuestaLayout.setHorizontalGroup(
            jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropuestaLayout.createSequentialGroup()
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPropuestaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFiltrarPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPropuestaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelPropuestaLayout.createSequentialGroup()
                                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPropuestaLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(2, 2, 2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPropuestaLayout.createSequentialGroup()
                                            .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel16)
                                                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12))
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(jLabel17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPropuestaLayout.createSequentialGroup()
                                        .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPropuPrecioE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextPropuMontoT)
                                    .addComponent(jTextPropuLugar)
                                    .addComponent(jTextPropuRetorno)
                                    .addComponent(jTextPropuEstado)
                                    .addComponent(jTextPropuCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jTextPropuTitulo)
                                    .addComponent(jTextPropuFechaR)
                                    .addComponent(jTextPropuTotalActual, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPropuestaLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel15)))
                .addGap(87, 87, 87))
        );
        jPanelPropuestaLayout.setVerticalGroup(
            jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFiltrarPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextPropuCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextPropuTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextPropuFechaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextPropuEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextPropuRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextPropuLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextPropuMontoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextPropuPrecioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPropuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextPropuTotalActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelColaboraciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setText("Monto:");

        jTextColabMonto.setEditable(false);

        jLabel21.setText("Fecha:");

        jTextColabFecha.setEditable(false);

        jLabel22.setText("Retorno Elegido:");

        jTextColabRetorno.setEditable(false);

        jTableColaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificador", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableColaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableColaboradoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableColaboradores);

        jLabel24.setText("Filtrar Colaboraciones:");

        jTextFiltrarColaboraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFiltrarColaboracionesActionPerformed(evt);
            }
        });
        jTextFiltrarColaboraciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFiltrarColaboracionesKeyReleased(evt);
            }
        });

        jLabel25.setText("Hora:");

        jTextColabHora.setEditable(false);

        jLabel7.setText("Detalle Colaboracion");

        javax.swing.GroupLayout jPanelColaboracionesLayout = new javax.swing.GroupLayout(jPanelColaboraciones);
        jPanelColaboraciones.setLayout(jPanelColaboracionesLayout);
        jPanelColaboracionesLayout.setHorizontalGroup(
            jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextColabRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextColabMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextColabHora, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextColabFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7)))
                    .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFiltrarColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanelColaboracionesLayout.setVerticalGroup(
            jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaboracionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFiltrarColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextColabMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextColabFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextColabHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColaboracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextColabRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
        );

        jPanelInfoUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Fecha Nacimiento:");

        jTextPropFechaN.setEditable(false);

        jLabel2.setText("Nombre:");

        jTextPropNombre.setEditable(false);

        jLabel3.setText("Apellido:");

        jTextPropApellido.setEditable(false);

        jLabel4.setText("Identificador:");

        jTextPropNick.setEditable(false);

        jLabel5.setText("Correo:");

        jTextPropCorreo.setEditable(false);

        jLabel6.setText("Informacion Proponente");

        jLabel23.setText("Fecha Desactivación:");

        jTextPropFechaD.setEditable(false);

        javax.swing.GroupLayout jPanelInfoUsuarioLayout = new javax.swing.GroupLayout(jPanelInfoUsuario);
        jPanelInfoUsuario.setLayout(jPanelInfoUsuarioLayout);
        jPanelInfoUsuarioLayout.setHorizontalGroup(
            jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoUsuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInfoUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPropFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPropNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoUsuarioLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextPropCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextPropApellido))
                        .addGap(37, 37, 37)
                        .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanelInfoUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(11, 11, 11)))
                        .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextPropNick, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jTextPropFechaD)))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoUsuarioLayout.setVerticalGroup(
            jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextPropNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextPropApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextPropNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jTextPropFechaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPropCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextPropFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)
                                .addGap(21, 21, 21))))
                    .addComponent(jPanelInfoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFiltrarColaboracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFiltrarColaboracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFiltrarColaboracionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VerProponenteDesactivado des = new VerProponenteDesactivado();
        inicio.Escritorio.add(des);
        this.setVisible(false);
        des.toFront();
        des.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTablePropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePropuestasMouseClicked
        int row = jTablePropuestas.rowAtPoint(evt.getPoint());

        String titulo = jTablePropuestas.getValueAt(row, 0).toString();

        DtConsultaPropuesta info = Fabrica.getInstance().getControladorPropCat().SeleccionarPropuesta(titulo, null);

        if (info != null) {
            jTextPropuCategoria.setText(info.getCategoria());
            jTextPropuEstado.setText(info.getEstadoActual());
            jTextPropuFechaR.setText(info.getFechaR());
            jTextPropuLugar.setText(info.getLugar());
            jTextPropuMontoT.setText(String.valueOf(info.getMontoTot()));
            jTextPropuPrecioE.setText(String.valueOf(info.getMontoE()));
            jTextPropuRetorno.setText(info.getTipoRetorno());
            jTextPropuTitulo.setText(info.getTitulo());
            jTextPropuTotalActual.setText(String.valueOf(info.getMontoActual()));
        }

        this.colabs = Fabrica.getInstance().getControladorPropCat().ListarColaboradores(titulo);
        this.LimpiarColaboraciones();
        if (colabs.size() > 0) {

            DefaultTableModel modelo = (DefaultTableModel) jTableColaboradores.getModel();
            modelo.setRowCount(0);

            for (int i = 0; i < colabs.size(); i++) {
                DtinfoColaborador colab = (DtinfoColaborador) colabs.get(i);
                Object[] datos = {colab.getNickname(), colab.getNombre(), colab.getApellido()};

                modelo.addRow(datos);
            }
            jTableColaboradores.addMouseListener(new MouseAdapter() {
            });
        }
    }//GEN-LAST:event_jTablePropuestasMouseClicked

    private void jTableColaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableColaboradoresMouseClicked
        int row = jTableColaboradores.rowAtPoint(evt.getPoint());

        String nick = jTableColaboradores.getValueAt(row, 0).toString();

        String titulo = jTextPropuTitulo.getText();

        DtColaboraciones colab = Fabrica.getInstance().getControladorPropCat().ObtenerColaboracion(nick, titulo);

        jTextColabFecha.setText(nick);

        java.util.Date utilDate = new java.util.Date();
        utilDate = colab.getFechaRealiz().getTime();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat g = new SimpleDateFormat("hh:mm:ss a");
        jTextColabFecha.setText(f.format(utilDate));
        jTextColabHora.setText(g.format(utilDate.getTime()));
        jTextColabMonto.setText(String.valueOf(colab.getMontoC()));

        if (colab.getEntradas()) {
            jTextColabRetorno.setText("Entradas");
        } else {
            jTextColabRetorno.setText("Porcentage");
        }
    }//GEN-LAST:event_jTableColaboradoresMouseClicked

    private void jTextFiltrarPropuestasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFiltrarPropuestasKeyReleased

        DefaultTableModel model = (DefaultTableModel) jTablePropuestas.getModel();
        model.setRowCount(0);

        for (int i = 0; i < jTablePropuestas.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }

        model = (DefaultTableModel) jTablePropuestas.getModel();
        model.setRowCount(0);

        Iterator it = listProp.iterator();
        while (it.hasNext()) {
            if (jTextFiltrarPropuestas.getText().isEmpty() && it.next().toString().contains(jTextFiltrarPropuestas.getText())) {
                Object[] datos = {it.next().toString()};
                model.addRow(datos);
            } else if (jTextFiltrarPropuestas.getText().isEmpty()) {
                Object[] datos = {it.next().toString()};
                model.addRow(datos);
            }
        }
    }//GEN-LAST:event_jTextFiltrarPropuestasKeyReleased

    private void jTextFiltrarColaboracionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFiltrarColaboracionesKeyReleased
        DefaultTableModel model = (DefaultTableModel) jTableColaboradores.getModel();

        model.setRowCount(0);

        for (int i = 0; i < jTableColaboradores.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }

        model = (DefaultTableModel) jTableColaboradores.getModel();
        model.setRowCount(0);

        for (int i = 0; i < this.colabs.size(); i++) {
            DtinfoColaborador colab = (DtinfoColaborador) this.colabs.get(i);
            if ((!jTextFiltrarColaboraciones.getText().isEmpty()) && colab.getNickname().contains(jTextFiltrarColaboraciones.getText())) {
                Object[] dat = {colab.getNickname(), colab.getNombre(), colab.getApellido()};
                model.addRow(dat);
            } else if (jTextFiltrarColaboraciones.getText().isEmpty()) {
                Object[] dat = {colab.getNickname(), colab.getNombre(), colab.getApellido()};
                model.addRow(dat);
            }
        }
    }//GEN-LAST:event_jTextFiltrarColaboracionesKeyReleased

    public void LimpiarColaboraciones() {
        jTextColabFecha.setText("");
        jTextColabFecha.setText("");
        jTextColabHora.setText("");
        jTextColabMonto.setText("");
        jTextColabRetorno.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelColaboraciones;
    private javax.swing.JPanel jPanelInfoUsuario;
    private javax.swing.JPanel jPanelPropuesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableColaboradores;
    private javax.swing.JTable jTablePropuestas;
    private javax.swing.JTextField jTextColabFecha;
    private javax.swing.JTextField jTextColabHora;
    private javax.swing.JTextField jTextColabMonto;
    private javax.swing.JTextField jTextColabRetorno;
    private javax.swing.JTextField jTextFiltrarColaboraciones;
    private javax.swing.JTextField jTextFiltrarPropuestas;
    private javax.swing.JTextField jTextPropApellido;
    private javax.swing.JTextField jTextPropCorreo;
    private javax.swing.JTextField jTextPropFechaD;
    private javax.swing.JTextField jTextPropFechaN;
    private javax.swing.JTextField jTextPropNick;
    private javax.swing.JTextField jTextPropNombre;
    private javax.swing.JTextField jTextPropuCategoria;
    private javax.swing.JTextField jTextPropuEstado;
    private javax.swing.JTextField jTextPropuFechaR;
    private javax.swing.JTextField jTextPropuLugar;
    private javax.swing.JTextField jTextPropuMontoT;
    private javax.swing.JTextField jTextPropuPrecioE;
    private javax.swing.JTextField jTextPropuRetorno;
    private javax.swing.JTextField jTextPropuTitulo;
    private javax.swing.JTextField jTextPropuTotalActual;
    // End of variables declaration//GEN-END:variables
}
